"""user

Revision ID: 66cc527c6e9b
Revises: 
Create Date: 2023-10-31 16:11:09.893144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66cc527c6e9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.CHAR(length=50), nullable=False),
    sa.Column('first_name', sa.CHAR(length=50), nullable=True),
    sa.Column('last_name', sa.CHAR(length=50), nullable=True),
    sa.Column('username', sa.CHAR(length=50), nullable=True),
    sa.Column('password', sa.CHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
