"""chande table user

Revision ID: 990d87c45b6f
Revises: 66cc527c6e9b
Create Date: 2023-10-31 16:48:31.116882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '990d87c45b6f'
down_revision = '66cc527c6e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('first_name',
               existing_type=sa.CHAR(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.CHAR(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.CHAR(length=50),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.CHAR(length=50),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_unique_constraint('unique_constraint_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint('unique_constraint_username', type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.String(),
               type_=sa.CHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.CHAR(length=50),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.CHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.CHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=50),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
