"""add event

Revision ID: c7b6ef0513d4
Revises: 50b27fba0fe1
Create Date: 2023-11-01 01:07:15.813338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7b6ef0513d4'
down_revision = '50b27fba0fe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('begin_at',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('end_at',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('end_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('begin_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
